name: Clippy check

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: 1.54
            features: ''
          - rust: 1.63
            features: ''
          - rust: 1.63
            features: 'std'
          - rust: 1.73
            features: 'std'
            cfgs: "--cfg loom"

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{matrix.rust}}
            components: clippy
            override: true
      - name: Clippy check
        run: RUSTFLAGS="${{matrix.cfgs}}" cargo clippy --features "${{matrix.features}}"
